### PR TITLE
Recipe navbar

### PR DESCRIPTION
**Pull request by Tufayel5**
This was for the recipe page on the navbar. Created side links that can be directed to other pages as well as showing recommended recipes in the overall page.

### CODE REVIEW

**Comment by PineappleBingo** [comment]
The recipe page is well structured and categorized by using a sidebar menu. Each recipe card design contains minimal info., and I think it is simple and neat.

**Review by PineappleBingo — APPROVED** [review]

**Review by PineappleBingo — DISMISSED** [review]
Seems like some of the changes that I already made are in conflict with your changes. Please review it and resolve the conflict. you may need to delete the contents of recipe.html that I made

**Review by brazilian-code — APPROVED** [review]
Looks great, we'll start trying to populate those containers using the API

**Review by KevPeter — APPROVED** [review]

**Review by nvidad — APPROVED** [review]

**Comment by Tufayel5** [comment]
> Seems like some of the changes that I already made are in conflict with your changes. Please review it and resolve the conflict. you may need to delete the contents of recipe.html that I made

I already deleted those files, you'll need to merge this and then you'll be able to see it.

**Review by AnthonyCampana — APPROVED** [review]
looks good keep it up

**Review by PineappleBingo — APPROVED** [review]

**Pull request merged**
