### PR TITLE
pre-commit config / HTML, Django Templates

### PR DESCRIPTION
**Pull request by PineappleBingo**
Pre-commit configuration
 - Prettier Mirror : HTML Linter
 - jinjalint : Django Templates

Fixed unclosed HTML Tag in header & footer.

### CODE REVIEW

**Comment by PineappleBingo** [comment]
Please review the changes

**Review by KevPeter — APPROVED** [review]
good changes, was this all to beautify the codebase?

**Review by brazilian-code — APPROVED** [review]
Looks good, the search bar is rather simple, but that's what we need for now. Once we from the backend get the API working and we can actually search we'll work on adding more fields to the search bar to make it more complete

**Comment by Tufayel5** [comment]
> good changes, was this all to beautify the codebase?

Yes this was to make it more presentable.

**Comment by Tufayel5** [comment]
Search bar looks good for now, as soon as the backend can start their work, we can update the search bar.

**Review by Tufayel5 — APPROVED** [review]

**Comment by PineappleBingo** [comment]
> good changes, was this all to beautify the codebase?

Yes, pre-commit will run Prettier to make out HTML code looks more organized and check any errors in HTML.

**Review by nvidad — APPROVED** [review]

**Pull request merged**
